[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Cameron Derwin <camderwin@gmail.com>"]

[dependencies]
argparse = "*"
image = "*"
iron = "*"
num = "0.1"

[lib]
name = "lib"
crate-type = ["dylib"]
